
--
-- Postgres SQL Schema dump automatic generated by geni
--


-- TABLES 

CREATE TABLE metrics (
 id integer  NOT NULL,
 keypresses integer  NOT NULL,
 mouse_clicks integer  NOT NULL,
 mouse_distance_in double precision  NOT NULL,
 mouse_distance_mi double precision  NOT NULL,
 scroll_steps integer  NOT NULL,
 timestamp timestamp without time zone  NOT NULL
);

CREATE TABLE metrics_summary (
 id integer  NOT NULL,
 last_updated timestamp with time zone ,
 total_keypresses bigint  NOT NULL,
 total_mouse_clicks bigint  NOT NULL,
 total_mouse_travel_in double precision  NOT NULL,
 total_mouse_travel_mi double precision  NOT NULL,
 total_scroll_steps bigint  NOT NULL
);

CREATE TABLE schema_migrations (
 id character varying (255) NOT NULL
);

-- CONSTRAINTS 

ALTER TABLE metrics ADD CONSTRAINT metrics_pkey PRIMARY KEY (id);

ALTER TABLE metrics_summary ADD CONSTRAINT metrics_summary_pkey PRIMARY KEY (id);

ALTER TABLE schema_migrations ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (id);

-- INDEXES 

CREATE UNIQUE INDEX metrics_pkey ON public.metrics USING btree (id)

CREATE UNIQUE INDEX metrics_summary_pkey ON public.metrics_summary USING btree (id)

CREATE UNIQUE INDEX schema_migrations_pkey ON public.schema_migrations USING btree (id)

-- SEQUENCES 

CREATE SEQUENCE metrics_id_seq AS integer START WITH 1 MINVALUE 1 MAXVALUE 2147483647 INCREMENT BY 1 CYCLE;

