// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
)

type Metric struct {
	ID              int64
	Keypresses      int64
	MouseClicks     int64
	MouseDistanceIn float64
	MouseDistanceMi float64
	ScrollSteps     int64
	Timestamp       sql.NullTime
}
