// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"time"
)

type Metric struct {
	ID               int32
	Keypresses       int32
	MouseClicks      int32
	MouseDistanceIn  float64
	MouseDistanceMi  float64
	ScrollDistanceIn float64
	ScrollDistanceMi float64
	Timestamp        time.Time
}
