// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package db

import (
	"context"
)

const createMetrics = `-- name: CreateMetrics :one
INSERT INTO metrics (
    keypresses, mouse_clicks, mouse_distance_in, mouse_distance_mi, scroll_steps
) VALUES (
    ?, ?, ?, ?, ?
)
RETURNING id, keypresses, mouse_clicks, mouse_distance_in, mouse_distance_mi, scroll_steps, timestamp
`

type CreateMetricsParams struct {
	Keypresses      int64
	MouseClicks     int64
	MouseDistanceIn float64
	MouseDistanceMi float64
	ScrollSteps     int64
}

func (q *Queries) CreateMetrics(ctx context.Context, arg CreateMetricsParams) (Metric, error) {
	row := q.db.QueryRowContext(ctx, createMetrics,
		arg.Keypresses,
		arg.MouseClicks,
		arg.MouseDistanceIn,
		arg.MouseDistanceMi,
		arg.ScrollSteps,
	)
	var i Metric
	err := row.Scan(
		&i.ID,
		&i.Keypresses,
		&i.MouseClicks,
		&i.MouseDistanceIn,
		&i.MouseDistanceMi,
		&i.ScrollSteps,
		&i.Timestamp,
	)
	return i, err
}
